-- Insert 20 NYC 311 tickets into the tickets table
-- Run with: heroku pg:psql --app=civitas-demo < backend/scripts/insert_20_tickets.sql

INSERT INTO ticket (ticket_subject, ticket_body, origin, status, priority, reporter_id, location_coordinates) VALUES
('Obstruction on 32 Street in Queens (unique_key: 67078272)', 'I am reporting a cone obstruction on 32 Street in the Queens borough. The cone is currently blocking a portion of the street, potentially causing a hazard for drivers and pedestrians. I am concerned that if this issue is not addressed, it may lead to accidents or disruptions in traffic flow. I would appreciate it if the city could remove or relocate the cone as soon as possible to ensure public safety.', 'phone', 'awaiting response', 'low', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.92458792215176, 40.761599665302725), 4326)),

('Damaged Guard Rail on Arthur Kill Road (unique_key: 67080953)', 'I am reporting a damaged guard rail on Arthur Kill Road, which poses a safety hazard to drivers and pedestrians. The guard rail appears to be bent and loose, and I am concerned that it could cause an accident if not repaired. I have noticed this issue while driving on Arthur Kill Road near the 3044 address, and I hope it can be addressed as soon as possible. I would appreciate it if the relevant authorities could inspect and repair the guard rail to ensure public safety.', 'phone', 'awaiting response', 'high', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-74.23128859672183, 40.54491883453047), 4326)),

('Unleashed Dog in Public Area (unique_key: 67076566)', 'I am reporting an unleashed dog roaming freely in the public area near 88-10 86 Street in Queens. As I was walking by, I saw the dog without a leash or an owner in sight, which is a concern for public safety. The dog appears to be a medium-sized breed and is currently wandering around the unfenced area, posing a potential threat to pedestrians and other animals. I kindly request that animal control be dispatched to the location to safely capture the dog and reunite it with its owner.', 'web form', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.85742463826716, 40.69055113111359), 4326)),

('Outdoor Dining Concern at 214 Greene Avenue, Brooklyn (unique_key: 67076839)', 'I am writing to express concern about the outdoor dining setup at the restaurant located at 214 Greene Avenue in Brooklyn. The current configuration appears to be obstructing pedestrian traffic and taking up a significant portion of the sidewalk, making it difficult for people to walk by. I am worried about the safety and accessibility of the area, especially for individuals with disabilities or families with strollers. I would appreciate it if the city could look into this matter and ensure that the outdoor dining area is compliant with city regulations.', 'web form', 'awaiting response', 'low', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.96278503418345, 40.68705425247828), 4326)),

('Outdoor Dining Concern at 214 Greene Avenue, Brooklyn (unique_key: 67075310)', 'I am writing to express concern about the outdoor dining setup at the restaurant located at 214 Greene Avenue in Brooklyn. The current configuration appears to be obstructing pedestrian traffic and taking up a significant portion of the sidewalk, making it difficult for people to walk by. As a frequent visitor to this area, I am worried about the safety and accessibility of the sidewalk, especially for individuals with disabilities or families with strollers. I would appreciate it if the city could look into this matter and ensure that the outdoor dining area is set up in a way that complies with city regulations and allows for safe passage.', 'web form', 'awaiting response', 'low', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.96278503418345, 40.68705425247828), 4326)),

('Failed Street Repair at 35-37 204 Street, Queens (unique_key: 67080952)', 'I am writing to report a failed street repair at 35-37 204 Street in Queens. The street was recently resurfaced, but the repair work has already started to deteriorate, with potholes and uneven pavement forming. This is not only causing damage to vehicles, but it''s also creating a hazardous condition for pedestrians and cyclists. I kindly request that the city sends a crew to reassess and redo the repair work to ensure the street is safe for everyone.', 'web form', 'awaiting response', 'high', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.78329747884915, 40.76589722417967), 4326)),

('Sidewalk Blocked by Construction at 834 Pacific Street, Brooklyn (unique_key: 67078147)', 'I am writing to report that the sidewalk at 834 Pacific Street in Brooklyn is currently blocked due to ongoing construction. The obstruction is causing pedestrians to walk into the street, which is a significant safety concern, especially for children and seniors. I am concerned that if this issue is not addressed promptly, it may lead to accidents or injuries. I would appreciate it if the city could take immediate action to ensure the sidewalk is cleared and made safe for pedestrians.', 'phone', 'awaiting response', 'high', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.96679055295567, 40.68076171575791), 4326)),

('Poor Ventilation Causing Indoor Air Quality Issues at 411 Butler Street (unique_key: 67078043)', 'I am concerned about the indoor air quality at my residence, 411 Butler Street, due to inadequate ventilation. The lack of proper airflow is causing stale air and moisture buildup, which is exacerbating allergy issues and creating an unpleasant living environment. I have tried to improve the situation by opening windows, but it''s not sufficient, and I believe a more permanent solution is needed to ensure healthy air circulation. I would appreciate it if someone could investigate and assist in resolving this issue.', 'phone', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.98056714793253, 40.679675192230306), 4326)),

('Rodent Sighting at Commercial Building in Queens (unique_key: 67085448)', 'I am writing to report a rat sighting at the commercial building located at 155-01 90 Avenue in Queens. I witnessed a rat scurrying around the premises, specifically near the entrance of the building, and I am concerned about the potential health risks this poses to the employees and customers who frequent this location. The rat was seen during daylight hours, which suggests that the infestation may be significant. I kindly request that the necessary measures be taken to address this issue and prevent further rodent activity.', 'web form', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.8021037797246, 40.7045939044023), 4326)),

('Unverified Food Establishment Permit at 10 Columbus Circle (unique_key: 67083725)', 'I am concerned that the restaurant located at 10 Columbus Circle in Manhattan may not have a valid permit or license to operate. As a frequent customer, I noticed that the establishment''s certificate of permit is not displayed prominently as required by law. I am worried about the potential health and safety implications of this oversight and would like the city to verify the status of their permit. I would appreciate it if someone could investigate this matter and ensure that the establishment is in compliance with all relevant regulations.', 'web form', 'awaiting response', 'low', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.98231026912883, 40.768273498505636), 4326)),

('Sidewalk Obstruction by Outdoor Dining Setup on MacDougal Street (unique_key: 67084024)', 'I am writing to report that the sidewalk in front of 81 MacDougal Street in Manhattan is currently blocked by an outdoor dining setup. The tables and chairs are extending beyond the designated area and into the pedestrian path, making it difficult for people to walk by. This obstruction is not only an inconvenience but also a safety hazard, especially for those with disabilities or families with strollers. I kindly request that the city take action to ensure the sidewalk is cleared and accessible to all pedestrians.', 'web form', 'awaiting response', 'high', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-74.00149371696034, 40.7288245809915), 4326)),

('Damaged Do Not Enter Street Sign on 101 Street (unique_key: 67076678)', 'I am writing to report a damaged street sign at 101 Street in Queens. The "Do Not Enter" sign is broken and hanging loosely, which could cause confusion for drivers and potentially lead to accidents. I am concerned about the safety of the community, especially during peak hours, and I believe it is essential to repair or replace the sign as soon as possible. I would appreciate it if someone could look into this matter and take the necessary actions to ensure the sign is restored to its proper condition.', 'text', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.86829282639488, 40.76181255620047), 4326)),

('Residential Disposal Complaint at 863 East 169 Street (unique_key: 67085462)', 'I am reporting a disposal issue at 863 East 169 Street in the Bronx, where a residential disposal bin has not been used. The bin is currently located on the sidewalk and appears to be unused, potentially causing an eyesore and a nuisance to the community. As a concerned citizen, I believe it is essential to address this issue to maintain the cleanliness and aesthetic appeal of our neighborhood. I would appreciate it if the relevant authorities could investigate and take necessary actions to resolve this matter.', 'phone', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.89697692220842, 40.829098657992446), 4326)),

('Rodent Sighting on Fulton Street (unique_key: 67078316)', 'I am writing to report a rodent sighting on Fulton Street in Brooklyn. Specifically, I saw a rat scurrying around the street/curbside area near 510 Fulton Street. The sighting occurred during daylight hours and I am concerned about the potential health risks associated with rodent infestations in the area. I would appreciate it if the city could investigate and take necessary measures to address this issue as soon as possible.', 'web form', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.98243213717063, 40.68948256141962), 4326)),

('Deceased Cat on Sidewalk at East 131 Street (unique_key: 67083974)', 'I am reporting a dead cat found on the sidewalk at East 131 Street in Manhattan. The cat appears to have been there for some time and is causing a disturbance in the area. I am concerned about the potential health and safety implications for nearby residents, especially children and pets. I kindly request that the city sends someone to collect the carcass as soon as possible.', 'phone', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.93788139358821, 40.80952516204141), 4326)),

('Residential Waste Disposal Issue on East 169 Street (unique_key: 67081053)', 'I am reporting a residential disposal complaint where waste has been left in front of a residence other than the one it belongs to, located at 865 East 169 Street in the Bronx. The trash is currently sitting on the sidewalk, creating an eyesore and potentially attracting pests. I am concerned that this may be a recurring issue and would like the city to address the matter as soon as possible. I would appreciate it if someone could investigate and ensure that the waste is properly disposed of and the responsible party is held accountable.', 'phone', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.89690832625504, 40.829060170670566), 4326)),

('Smoking in Designated Smoke-Free Area at 1120 Rosedale Avenue (unique_key: 67075324)', 'I am concerned about the repeated instances of smoking and vaping in the residential building located at 1120 Rosedale Avenue in the Bronx. Despite being a designated smoke-free area, residents and visitors are frequently seen smoking and vaping in and around the building, posing a health risk to others. I kindly request that the authorities take necessary measures to enforce the smoke-free policy and ensure a healthier environment for all residents. I would appreciate it if this matter could be addressed promptly to prevent further incidents.', 'web form', 'awaiting response', 'low', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-73.86836761149952, 40.82808419778328), 4326)),

('Dead Deer on Forest Hill Road (unique_key: 67075282)', 'I am reporting a dead deer on Forest Hill Road in Staten Island. The animal is located on the street and appears to have been there for some time. I am concerned about the potential health and safety risks it may pose to the community, as well as the unpleasant odor it is causing. I would appreciate it if someone could arrange for its removal as soon as possible.', 'phone', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-74.16982709252079, 40.57083566003277), 4326)),

('Obstruction on Delafield Avenue (unique_key: 67082522)', 'I am reporting a cone obstructing the street on Delafield Avenue in Staten Island. The cone is currently located on the street and is causing a hazard for drivers and pedestrians. I am concerned that it may cause an accident if not removed promptly. I would appreciate it if the city could send someone to remove the cone as soon as possible.', 'web form', 'awaiting response', 'low', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-74.12292190659542, 40.62934319760249), 4326)),

('Dead Deer on Forest Hill Road (unique_key: 67081088)', 'I am reporting a deceased deer on Forest Hill Road in Staten Island. The animal appears to have been struck by a vehicle and is currently lying in the street, posing a potential hazard to drivers and pedestrians. I am concerned about the safety and sanitation of the area, and I kindly request that the city arrange for its removal as soon as possible. I would appreciate it if this matter could be addressed promptly to prevent any further issues.', 'web form', 'awaiting response', 'medium', 'b3cdcf8f-3c7a-4001-b7fb-646e909d2fa9', ST_SetSRID(ST_MakePoint(-74.16982709252079, 40.57083566003277), 4326));

-- Show count of tickets after insert
SELECT COUNT(*) as total_tickets FROM tickets;
