"""create initial civitas schema

Revision ID: 75cca2534dbe
Revises: ef481ff6b572
Create Date: 2025-12-02 11:27:00.190460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '75cca2534dbe'
down_revision: Union[str, None] = 'ef481ff6b572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civitas_role',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_civitas_role_role_name'), 'civitas_role', ['role_name'], unique=True)
    op.create_table('civitas_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('google_avatar_url', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_civitas_user_email'), 'civitas_user', ['email'], unique=True)
    op.create_index(op.f('ix_civitas_user_google_id'), 'civitas_user', ['google_id'], unique=True)
    op.create_index(op.f('ix_civitas_user_phone_number'), 'civitas_user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_civitas_user_user_id'), 'civitas_user', ['user_id'], unique=False)
    op.create_table('support_crew',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crew_type', sa.Enum('POTHOLE_CREW', 'DRAIN_CREW', 'TREE_CREW', 'SIGN_CREW', 'SNOW_CREW', 'SANITATION_CREW', name='supportcrewtype'), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_edited', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='supportcrewstatus'), nullable=False),
    sa.Column('location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('idx_support_crew_location_coordinates', 'support_crew', ['location_coordinates'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_support_crew_team_id'), 'support_crew', ['team_id'], unique=False)
    op.create_index(op.f('ix_support_crew_team_name'), 'support_crew', ['team_name'], unique=True)
    op.create_table('crew_leads_association',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['support_crew.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['civitas_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('crew_members_association',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['support_crew.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['civitas_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('label',
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('label_description', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['civitas_user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_label_created_by'), 'label', ['created_by'], unique=False)
    op.create_index(op.f('ix_label_label_id'), 'label', ['label_id'], unique=False)
    op.create_index(op.f('ix_label_label_name'), 'label', ['label_name'], unique=True)
    op.create_table('ticket',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('ticket_subject', sa.String(), nullable=False),
    sa.Column('ticket_body', sa.Text(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin', sa.Enum('PHONE', 'WEB_FORM', 'TEXT', name='ticketorigin'), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_RESPONSE', 'RESPONSE_IN_PROGRESS', 'RESOLVED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='ticketpriority'), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['civitas_user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index('idx_ticket_location_coordinates', 'ticket', ['location_coordinates'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ticket_reporter_id'), 'ticket', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_ticket_ticket_id'), 'ticket', ['ticket_id'], unique=False)
    op.create_table('user_roles_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['civitas_role.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['civitas_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('ticket_comment',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('comment_body', sa.Text(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('time_edited', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commenter', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['commenter'], ['civitas_user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_ticket_comment_comment_id'), 'ticket_comment', ['comment_id'], unique=False)
    op.create_index(op.f('ix_ticket_comment_commenter'), 'ticket_comment', ['commenter'], unique=False)
    op.create_index(op.f('ix_ticket_comment_ticket_id'), 'ticket_comment', ['ticket_id'], unique=False)
    op.create_table('ticket_crew_assignees_association',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['support_crew.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'team_id')
    )
    op.create_table('ticket_labels_association',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.label_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'label_id')
    )
    op.create_table('ticket_update_log',
    sa.Column('update_log_id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_of_origin', sa.UUID(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_of_origin'], ['civitas_user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('update_log_id')
    )
    op.create_index(op.f('ix_ticket_update_log_ticket_id'), 'ticket_update_log', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_update_log_update_log_id'), 'ticket_update_log', ['update_log_id'], unique=False)
    op.create_index(op.f('ix_ticket_update_log_user_of_origin'), 'ticket_update_log', ['user_of_origin'], unique=False)
    op.create_table('ticket_user_assignees_association',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['civitas_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_user_assignees_association')
    op.drop_index(op.f('ix_ticket_update_log_user_of_origin'), table_name='ticket_update_log')
    op.drop_index(op.f('ix_ticket_update_log_update_log_id'), table_name='ticket_update_log')
    op.drop_index(op.f('ix_ticket_update_log_ticket_id'), table_name='ticket_update_log')
    op.drop_table('ticket_update_log')
    op.drop_table('ticket_labels_association')
    op.drop_table('ticket_crew_assignees_association')
    op.drop_index(op.f('ix_ticket_comment_ticket_id'), table_name='ticket_comment')
    op.drop_index(op.f('ix_ticket_comment_commenter'), table_name='ticket_comment')
    op.drop_index(op.f('ix_ticket_comment_comment_id'), table_name='ticket_comment')
    op.drop_table('ticket_comment')
    op.drop_table('user_roles_association')
    op.drop_index(op.f('ix_ticket_ticket_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_reporter_id'), table_name='ticket')
    op.drop_index('idx_ticket_location_coordinates', table_name='ticket', postgresql_using='gist')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_label_label_name'), table_name='label')
    op.drop_index(op.f('ix_label_label_id'), table_name='label')
    op.drop_index(op.f('ix_label_created_by'), table_name='label')
    op.drop_table('label')
    op.drop_table('crew_members_association')
    op.drop_table('crew_leads_association')
    op.drop_index(op.f('ix_support_crew_team_name'), table_name='support_crew')
    op.drop_index(op.f('ix_support_crew_team_id'), table_name='support_crew')
    op.drop_index('idx_support_crew_location_coordinates', table_name='support_crew', postgresql_using='gist')
    op.drop_table('support_crew')
    op.drop_index(op.f('ix_civitas_user_user_id'), table_name='civitas_user')
    op.drop_index(op.f('ix_civitas_user_phone_number'), table_name='civitas_user')
    op.drop_index(op.f('ix_civitas_user_google_id'), table_name='civitas_user')
    op.drop_index(op.f('ix_civitas_user_email'), table_name='civitas_user')
    op.drop_table('civitas_user')
    op.drop_index(op.f('ix_civitas_role_role_name'), table_name='civitas_role')
    op.drop_table('civitas_role')
    # ### end Alembic commands ###
